<script setup lang="ts">
import { useDocUpdate } from '@/hooks/use-doc-update';
import { ref } from 'vue';

const doc = ref<HTMLElement>()
useDocUpdate(doc)
</script>
<template>
  <div ref="doc">
    <h1>Keyboard 键盘管理</h1>
<p>Keyboard 用于注册快捷键或执行快捷键等操作。</p>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">通过编辑器实例或通过 useContext 勾子获取 Keyboard 的实例。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 方法1</span></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;keyboard = editor.<span class="tb-hl-function">get</span>(Keyboard)</div><div class="tb-code-line"><span class="tb-hl-comment">// 方法2</span></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;keyboard = injector.<span class="tb-hl-function">get</span>(Keyboard)</div><div class="tb-code-line"><span class="tb-hl-comment">// 方法3</span></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;yourComponent =&nbsp;<span class="tb-hl-function">defineComponent</span>({</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-function">setup</span>() {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">const</span>&nbsp;keyboard =&nbsp;<span class="tb-hl-function">useContext</span>(Keyboard)</div><div class="tb-code-line">&nbsp;&nbsp;}</div><div class="tb-code-line">})</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<h2>addZenCodingInterceptor() 注册语法糖</h2>
<p>注册语法糖（如 Markdown 语法支持），Textbus 会在用户输入时，根据用户输入的内容实时匹配已注册的配置项，当某一项匹配成功时，则会调用配置项指定的 action 方法。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">addZenCodingInterceptor</span>(interceptor: ZenCodingInterceptor): {</div><div class="tb-code-line">&nbsp;&nbsp;remove: () =&gt;&nbsp;<span class="tb-hl-keyword">void</span>;</div><div class="tb-code-line">};</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<p>配置项：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">ZenCodingInterceptor</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-comment">/** 匹配字符 */</span></div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-function">match</span>(key:&nbsp;<span class="tb-hl-builtin">string</span>):&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-comment">/** 触发键 */</span></div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-keyword">try</span>(key:&nbsp;<span class="tb-hl-builtin">string</span>):&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-comment">/** 触发执行的方法 */</span></div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-function">action</span>(content:&nbsp;<span class="tb-hl-builtin">string</span>):&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">}</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<tb-timeline>
  <div class="tb-timeline-item tb-timeline-item-primary">
    <div class="tb-timeline-line"></div>
    <div title="点击切换颜色" class="tb-timeline-icon"></div>
    <div class="tb-timeline-content">
      <div><strong style="font-size:18px">match(str: string)</strong></div>
      <p>用于匹配当前输入的字符串，str 为当前用户在插槽输入的字符串。</p>
    </div>
  </div>
  <div class="tb-timeline-item tb-timeline-item-primary">
    <div class="tb-timeline-line"></div>
    <div title="点击切换颜色" class="tb-timeline-icon"></div>
    <div class="tb-timeline-content">
      <div><strong style="font-size:18px">try(key: string)</strong></div>
      <p>用于尝试触发语法糖转换，key 为当前用户输入的键位 key，如回车键为 Enter。当返回为 true 时，则会调用 match 方法，并传入当前插槽的内容，用于匹配是否转换。</p>
    </div>
  </div>
  <div class="tb-timeline-item tb-timeline-item-primary">
    <div class="tb-timeline-line"></div>
    <div title="点击切换颜色" class="tb-timeline-icon"></div>
    <div class="tb-timeline-content">
      <div><strong style="font-size:18px">action(str: string)</strong></div>
      <p>当 match 方法匹配成功时，则会调用 action 方法，并传入用户在插槽中输入的字符串。你可以在此函数中修改文档内容，实现实时转换功能。</p>
    </div>
  </div>
</tb-timeline>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;shortcut = keyboard.<span class="tb-hl-function">addZenCodingInterceptor</span>({</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-comment">// 当用户按下 Enter 时，尝试转换</span></div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-keyword">try</span>(key:&nbsp;<span class="tb-hl-builtin">string</span>) {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">return</span>&nbsp;key ===&nbsp;<span class="tb-hl-string">'Enter'</span></div><div class="tb-code-line">&nbsp;&nbsp;},</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-comment">// 匹配用户当前输入的内容是否为 ```</span></div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-function">match</span>(str:&nbsp;<span class="tb-hl-builtin">string</span>) {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">return</span>&nbsp;str ===&nbsp;<span class="tb-hl-string">'```'</span></div><div class="tb-code-line">&nbsp;&nbsp;},</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-comment">// 当匹配成功时要执行的动作</span></div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-function">action</span>() {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-comment">// 创建一个代码块组件，替换当前光标所在组件，并把光标重新设置到代码块组件的第一个位置</span></div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">const</span>&nbsp;pre = preComponent.<span class="tb-hl-function">createInstance</span>(injector)</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;commander.<span class="tb-hl-function">replaceContent</span>(selection.commonAncestorComponent, pre)</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;selection.<span class="tb-hl-function">selectFirstPosition</span>(pre)</div><div class="tb-code-line">&nbsp;&nbsp;}</div><div class="tb-code-line">})</div><div class="tb-code-line"><br></div><div class="tb-code-line"><span class="tb-hl-comment">// 取消注册快捷键</span></div><div class="tb-code-line">shortcut.<span class="tb-hl-function">remove</span>()</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<h2>addShortcut() 注册快捷键</h2>
<p>注册快捷键，Textbus 会在用户操作时，实时匹配已注册的快捷键，并调用相应回调。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">addShortcut</span>(shortcut: Shortcut): {</div><div class="tb-code-line">&nbsp;&nbsp;remove: () =&gt;&nbsp;<span class="tb-hl-keyword">void</span>;</div><div class="tb-code-line">};</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<p>配置项：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content tb-color-content-highlight"><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">Key</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;match: RegExp | ((key:&nbsp;<span class="tb-hl-builtin">string</span>) =&gt;&nbsp;<span class="tb-hl-builtin">boolean</span>);</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;name:&nbsp;<span class="tb-hl-builtin">string</span>&nbsp;|&nbsp;<span class="tb-hl-builtin">string</span>[];</div><div class="tb-code-line">}</div><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">Keymap</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;ctrlKey?:&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;shiftKey?:&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;altKey?:&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;key:&nbsp;<span class="tb-hl-builtin">string</span>&nbsp;|&nbsp;<span class="tb-hl-builtin">string</span>[] | Key;</div><div class="tb-code-line">}</div><div class="tb-code-line-emphasize tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">Shortcut</span>&nbsp;{</div><div class="tb-code-line-emphasize tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;keymap: Keymap;</div><div class="tb-code-line-emphasize tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-function">action</span>(key:&nbsp;<span class="tb-hl-builtin">string</span>):&nbsp;<span class="tb-hl-builtin">boolean</span>&nbsp;|&nbsp;<span class="tb-hl-keyword">void</span>;</div><div class="tb-code-line-emphasize tb-code-line">}</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">keyboard.<span class="tb-hl-function">addShortcut</span>({</div><div class="tb-code-line">&nbsp;&nbsp;keymap: {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;ctrlKey:&nbsp;<span class="tb-hl-boolean">true</span>,</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;key:&nbsp;<span class="tb-hl-string">'s'</span></div><div class="tb-code-line">&nbsp;&nbsp;},</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-function">action</span>() {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-builtin">console</span>.<span class="tb-hl-function">log</span>(<span class="tb-hl-string">'用户按下了 Ctrl + S'</span>)</div><div class="tb-code-line">&nbsp;&nbsp;}</div><div class="tb-code-line">})</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<h2>execShortcut() 触发快捷键</h2>
<p>根据配置项触发已注册的快捷键。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">execShortcut</span>(keymapState: KeymapState):&nbsp;<span class="tb-hl-builtin">boolean</span>;</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<p>配置项：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">KeymapState</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;ctrlKey:&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">&nbsp;&nbsp;altKey:&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">&nbsp;&nbsp;shiftKey:&nbsp;<span class="tb-hl-builtin">boolean</span>;</div><div class="tb-code-line">&nbsp;&nbsp;key:&nbsp;<span class="tb-hl-builtin">string</span>;</div><div class="tb-code-line">}</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<p>如触发保存：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">keyboard.<span class="tb-hl-function">execShortcut</span>({</div><div class="tb-code-line">&nbsp;&nbsp;ctrlKey:&nbsp;<span class="tb-hl-boolean">true</span>,</div><div class="tb-code-line">&nbsp;&nbsp;altKey:&nbsp;<span class="tb-hl-boolean">false</span>,</div><div class="tb-code-line">&nbsp;&nbsp;shiftKey:&nbsp;<span class="tb-hl-boolean">false</span>,</div><div class="tb-code-line">&nbsp;&nbsp;key:&nbsp;<span class="tb-hl-string">'s'</span></div><div class="tb-code-line">})</div></div><span class="tb-pre-lang">TypeScript</span></pre>
  </div>
</template>