<script setup lang="ts">
import { useDocUpdate } from '@/hooks/use-doc-update';
import { ref } from 'vue';

const doc = ref<HTMLElement>()
useDocUpdate(doc)
</script>
<template>
  <div ref="doc">
    <h1>Selection 选区</h1>
<p>选区用于选择文档中的内容，或控制光标位置，在文档编写过程中，用户大多数时候都是根据光标或选区来做出操作。你可以根据自己的需要监听选区的变化，或设置选区。</p>
<p>通过编辑器实例或通过 useContext 勾子获取 Selection 的实例。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 方法1</span></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;selection= editor.<span class="tb-hl-function">get</span>(Selection)</div><div class="tb-code-line"><span class="tb-hl-comment">// 方法2</span></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;selection= injector.<span class="tb-hl-function">get</span>(Selection)</div><div class="tb-code-line"><span class="tb-hl-comment">// 方法3</span></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;yourComponent =&nbsp;<span class="tb-hl-function">defineComponent</span>({</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-function">setup</span>() {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">const</span>&nbsp;selection=&nbsp;<span class="tb-hl-function">useContext</span>(Selection)</div><div class="tb-code-line">&nbsp;&nbsp;}</div><div class="tb-code-line">})</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>onChange 监听选区变化</h2>
<p>可观察对象，当选区变化时触发。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">onChange: Observable&lt;AbstractSelection |&nbsp;<span class="tb-hl-keyword">null</span>&gt;;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">selection.onChange.<span class="tb-hl-function">subscribe</span>(() =&gt; {</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-builtin">console</span>.<span class="tb-hl-function">log</span>(<span class="tb-hl-string">'选区发生变化了'</span>)</div><div class="tb-code-line">})</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>isSelected 是否有选区</h2>
<p>只读，当 Selection 中的焦点和锚点插槽都存在时，值为 true，否则为 false</p>
<h2>isCollapsed 选区是否闭合</h2>
<p>只读，当选区的锚点和焦点在同一位置时，值为 true，否则为 false。</p>
<h2>startSlot 开始插槽</h2>
<p>只读，选区的开始插槽。开始插槽在文档中的位置总是位于结束插槽的前面，当选区为闭合时，开始插槽和结束插槽相等。当选区没有选中文档中任意位置时，值为 null</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">startSlot: Slot&lt;<span class="tb-hl-builtin">any</span>&gt; |&nbsp;<span class="tb-hl-keyword">null</span></div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>endSlot 结束插槽</h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">只读，选区的结束插槽。结束插槽在文档中的位置总是位于开始插槽的后面，当选区为闭合时，结束插槽和开始插槽相等。当选区没有选中文档中任意位置时，值为 null</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">startSlot: Slot&lt;<span class="tb-hl-builtin">any</span>&gt; |&nbsp;<span class="tb-hl-keyword">null</span></div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>startOffset 开始插槽偏移量</h2>
<p>只读，选区在开始插槽的偏移量。只与插槽的内容相关，与插槽的格式和属性无关。当选区没有选中文档中任意位置时，值为 null。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">startOffset:&nbsp;<span class="tb-hl-builtin">number</span>&nbsp;|&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>endOffset 结束插槽偏移量</h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">只读，选区结束插槽的偏移量。只与插槽的内容相关，与插槽的格式和属性无关。当选区没有选中文档中任意位置时，值为 null。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">endOffset:&nbsp;<span class="tb-hl-builtin">number</span>&nbsp;|&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>anchorSlot 锚点插槽</h2>
<p>只读，锚点插槽,，一般指鼠标按下的位置的插槽。<span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">当选区没有选中文档中任意位置时，值为 null。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">anchorSlot: Slot&lt;<span class="tb-hl-builtin">any</span>&gt; |&nbsp;<span class="tb-hl-keyword">null</span></div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>focusSlot 焦点插槽</h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">只读，焦点插槽,，一般指鼠标抬起的位置的插槽。当选区没有选中文档中任意位置时，值为 null。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">focusSlot: Slot&lt;<span class="tb-hl-builtin">any</span>&gt; |&nbsp;<span class="tb-hl-keyword">null</span></div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>anchorOffset 锚点插槽偏移量</h2>
<p>只读，选区锚点插槽的偏移量。<span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">当选区没有选中文档中任意位置时，值为 null。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">anchorOffset:&nbsp;<span class="tb-hl-builtin">number</span>&nbsp;|&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>focusOffset 焦点插槽偏移量</h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">只读，选区焦点插槽的偏移量。当选区没有选中文档中任意位置时，值为 null。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">focusOffset:&nbsp;<span class="tb-hl-builtin">number</span>&nbsp;|&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>commonAncestorSlot 公共父插槽</h2>
<p>只读，选区焦点插槽和锚点插槽公共父插槽。<span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">当选区没有选中文档中任意位置时，值为 null。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">commonAncestorSlot: Slot |&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>commonAncestorComponent 公共父组件</h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">只读，选区焦点插槽和锚点插槽公共父组件。当选区没有选中文档中任意位置时，值为 null。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">commonAncestorComponent: ComponentInstance |&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>nativeSelectionDelegate 是否代理原生选区</h2>
<p>可读写，用于设置是否代理原生选区。</p>
<p>Textbus 的 Selection 是脱离于具体平台实现的。通过选区操作文档，不完全依赖于具体平台的实现。在默认情况下，<span style="color:rgb(73, 80, 96)">nativeSelectionDelegate 的值为 true，Textbus 会自动双向同步抽象选区的原生选区，即原生选区变化时，会自动映射到 Textbus 的抽象选区，当抽象选区变化时，Textbus 会根据一定规则和时机，同步到原生选区。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line">nativeSelectionDelegate:&nbsp;<span class="tb-hl-builtin">boolean</span></div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 代理原生选区</span></div><div class="tb-code-line">selection.nativeSelectionDelegate =&nbsp;<span class="tb-hl-boolean">true</span></div><div class="tb-code-line"><span class="tb-hl-comment">// 取消代理原生选区</span></div><div class="tb-code-line">selection.nativeSelectionDelegate =&nbsp;<span class="tb-hl-boolean">false</span></div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>createSnapshot() 创建快照</h2>
<p>创建一个当前选区的快照，用于后面恢复。注意，只有在恢复时，快照缓存的选区位置的插槽和偏移量还存在，才能恢复，否则恢复将会失败。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">createSnapshot</span>(): SelectionSnapshot;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>选区快照类型：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">/**</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* 选区快照</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;*/</span></div><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">SelectionSnapshot</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-comment">/**</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* 恢复选区</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;* @param syncNative 是否同步原生选区</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;*/</span></div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-function">restore</span>(syncNative?:&nbsp;<span class="tb-hl-builtin">boolean</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div><div class="tb-code-line">}</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;snapshot = selection.<span class="tb-hl-function">createSnapshot</span>()</div><div class="tb-code-line"><br></div><div class="tb-code-line"><span class="tb-hl-comment">// 操作数据...</span></div><div class="tb-code-line"><br></div><div class="tb-code-line"><span class="tb-hl-comment">// 还原选区</span></div><div class="tb-code-line">snapshot.<span class="tb-hl-function">restore</span>()</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>setBaseAndExtent() 设置选区</h2>
<p>设置选区的锚点位置和焦点位置。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-comment">/**</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* 设置锚点和焦点的位置</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* @param anchorSlot 锚点插槽</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* @param anchorOffset 锚点偏移量</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* @param focusSlot 焦点插槽</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* @param focusOffset 焦点偏移量</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;*/</span></div><div class="tb-code-line"><span class="tb-hl-function">setBaseAndExtent</span>(anchorSlot: Slot, anchorOffset:&nbsp;<span class="tb-hl-builtin">number</span>, focusSlot: Slot, focusOffset:&nbsp;<span class="tb-hl-builtin">number</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">selection.<span class="tb-hl-function">setBaseAndExtent</span>(anchorSlot,&nbsp;<span class="tb-hl-number">3</span>, focusSlot,&nbsp;<span class="tb-hl-number">5</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>setAnchor() 设置锚点</h2>
<p>设置选区锚点位置。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">setAnchor</span>(slot: Slot, offset:&nbsp;<span class="tb-hl-builtin">number</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">selection.<span class="tb-hl-function">setAnchor</span>(slot,&nbsp;<span class="tb-hl-number">4</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>setFocus() 设置焦点</h2>
<p>设置选区焦点位置。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">setFocus</span>(slot: Slot, offset:&nbsp;<span class="tb-hl-builtin">number</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">示例：</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">selection.<span class="tb-hl-function">setFocus</span>(slot,&nbsp;<span class="tb-hl-number">2</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>setPosition() 设置选区</h2>
<p>同时设置选区的锚点和焦点位置。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">setPosition</span>(slot: Slot, offset:&nbsp;<span class="tb-hl-builtin">number</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">示例：</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">selection.<span class="tb-hl-function">setPosition</span>(slot,&nbsp;<span class="tb-hl-number">1</span>)</div><div class="tb-code-line"><span class="tb-hl-comment">// 等效于</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">setBaseAndExtent</span>(slot,&nbsp;<span class="tb-hl-number">1</span>, slot,&nbsp;<span class="tb-hl-number">1</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>selectSlot() 选择插槽</h2>
<p>选中插槽的所有内容。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">selectSlot</span>(slot: Slot):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">selection.<span class="tb-hl-function">selectSlot</span>(slot)</div><div class="tb-code-line"><span class="tb-hl-comment">// 等效于</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">setBaseAndExtent</span>(slot,&nbsp;<span class="tb-hl-number">0</span>, slot, slot.length)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>selectFirstPosition() 设置选区</h2>
<p>将选区设置到组件内可编辑内容的第一个位置。如当前组件的第一个插槽的第一位为带插槽的块组件，则会继续下内查找。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">selectFirstPosition</span>(componentInstance: ComponentInstance, isRestore?:&nbsp;<span class="tb-hl-builtin">boolean</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 设置选区到第一个位置</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectFirstPosition</span>(component)</div><div class="tb-code-line"><span class="tb-hl-comment">// 设置并立即同步到原生选区</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectFirstPosition</span>(component,&nbsp;<span class="tb-hl-boolean">true</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>selectLastPosition() 设置选区</h2>
<p>将选区设置到组件最后一个插槽的最后一个位置。<span style="color:rgb(73, 80, 96)">如当前组件的最后一个插槽的最后一位为带插槽的块组件，则会继续下内查找。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">selectLastPosition</span>(componentInstance: ComponentInstance, isRestore?:&nbsp;<span class="tb-hl-builtin">boolean</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">示例：</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 设置选区到最后一个位置</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectLastPosition</span>(component)</div><div class="tb-code-line"><span class="tb-hl-comment">// 设置并立即同步到原生选区</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectLastPosition</span>(component,&nbsp;<span class="tb-hl-boolean">true</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>selectComponentFront() 设置选区</h2>
<p>将选区设置在组件之前。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">selectComponentFront</span>(componentInstance: ComponentInstance, isRestore?:&nbsp;<span class="tb-hl-builtin">boolean</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 设置选区到组件之前</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectComponentFront</span>(component)</div><div class="tb-code-line"><span class="tb-hl-comment">// 设置并立即同步到原生选区</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectComponentFront</span>(component,&nbsp;<span class="tb-hl-boolean">true</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>selectComponentEnd() 设置选区</h2>
<p>将选区设置在组件之后。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">selectComponentEnd</span>(componentInstance: ComponentInstance, isRestore?:&nbsp;<span class="tb-hl-builtin">boolean</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">示例：</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 设置选区到组件之后</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectComponentEnd</span>(component)</div><div class="tb-code-line"><span class="tb-hl-comment">// 设置并立即同步到原生选区</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectComponentEnd</span>(component,&nbsp;<span class="tb-hl-boolean">true</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>selectChildSlots() 选择所有子插槽</h2>
<p>选中组件所有子插槽。如果当前组件没有子插槽，则会选中当前组件。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">selectChildSlots</span>(componentInstance: ComponentInstance, isRestore?:&nbsp;<span class="tb-hl-builtin">boolean</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">示例：</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 设置选区选中所有子插槽</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectChildSlots</span>(component)</div><div class="tb-code-line"><span class="tb-hl-comment">// 设置并立即同步到原生选区</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectChildSlots</span>(component,&nbsp;<span class="tb-hl-boolean">true</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>selectComponent() 选择组件</h2>
<p>选中一个组件。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">selectComponent</span>(componentInstance: ComponentInstance, isRestore?:&nbsp;<span class="tb-hl-builtin">boolean</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">示例：</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 设置选区选中组件</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectComponent</span>(component)</div><div class="tb-code-line"><span class="tb-hl-comment">// 设置并立即同步到原生选区</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">selectComponent</span>(component,&nbsp;<span class="tb-hl-boolean">true</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>toPrevious() 向前移动光标</h2>
<p>光标移动到前一个位置。</p>
<h2>toNext() 向后移动光标</h2>
<p>光标移动到后一个位置。</p>
<h2>toPreviousLine() 移动到上一行</h2>
<p>光标移动到上一行。</p>
<h2>toNextLine() 移动到下一行</h2>
<p>光标移动到下一行。</p>
<h2>wrapToAfter() 向后框选</h2>
<p>向后框选。</p>
<h2>wrapToBefore() 向前框选</h2>
<p>向前框选。</p>
<h2>wrapToTop() 向上一行框选</h2>
<p>向上框选。</p>
<h2>wrapToBottom() 向下一行框选</h2>
<p>向下框选。</p>
<h2>collapse() 闭合选区</h2>
<p><span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">将选区开始位置和结束位置设置在同一个位置。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">collapse</span>(toStart?:&nbsp;<span class="tb-hl-builtin">boolean</span>):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 将选区的开始位置设置为选区的结束位置</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">collapse</span>()</div><div class="tb-code-line"><span class="tb-hl-comment">// 将选区的结束位置设置为选区的开始位置</span></div><div class="tb-code-line">selection.<span class="tb-hl-function">collapse</span>(<span class="tb-hl-boolean">true</span>)</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2 style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">unSelect() 取消选区</span></h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">取消选区。</span></p>
<h2 style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">selectAll() 全选</span></h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">全选。</span></p>
<h2>restore() 同步原生选区</h2>
<p>同步 Textbus 选区到原生选区。</p>
<h2>getPaths() 获取选区路径</h2>
<p>获取选区路径。返回当前选区的锚点插槽及偏移量和焦点插槽及偏移量在文档中的路径。由两组数字表示。当没有选区时，返回两个空数组。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">getPaths</span>(): SelectionPaths;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>path 类型：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">/**</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* 选区锚点和焦点的绝对路径</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;*/</span></div><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">SelectionPaths</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;anchor:&nbsp;<span class="tb-hl-builtin">number</span>[];</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;focus:&nbsp;<span class="tb-hl-builtin">number</span>[];</div><div class="tb-code-line">}</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;paths = selection.<span class="tb-hl-function">getPaths</span>()</div><div class="tb-code-line"><br></div><div class="tb-code-line"><span class="tb-hl-builtin">console</span>.<span class="tb-hl-function">log</span>(paths)</div><div class="tb-code-line"><span class="tb-hl-comment">// {anchor: [0,2,44],focus:[0,2,57]}</span></div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>usePaths() 设置选区路径</h2>
<p>根据传入的绝对路径设置选区。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">usePaths</span>(paths: SelectionPaths):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">selection.<span class="tb-hl-function">usePaths</span>({</div><div class="tb-code-line">&nbsp;&nbsp;anchor: [<span class="tb-hl-number">0</span>,&nbsp;<span class="tb-hl-number">3</span>,&nbsp;<span class="tb-hl-number">44</span>,&nbsp;<span class="tb-hl-number">2</span>],</div><div class="tb-code-line">&nbsp;&nbsp;focus: [<span class="tb-hl-number">0</span>,&nbsp;<span class="tb-hl-number">4</span>,&nbsp;<span class="tb-hl-number">0</span>,&nbsp;<span class="tb-hl-number">6</span>]</div><div class="tb-code-line">})</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>getNextPosition() 获取后一个位置</h2>
<p>根据焦点位置，获取后一个选区位置。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">getNextPosition</span>(): SelectionPosition |&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>位置类型：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">/**</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* 插槽偏移量</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;*/</span></div><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">SelectionPosition</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;slot: Slot;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;offset:&nbsp;<span class="tb-hl-builtin">number</span>;</div><div class="tb-code-line">}</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>getPreviousPosition() 获取前一个位置</h2>
<p>根据焦点位置，获取前一个选区位置。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">getNextPosition</span>(): SelectionPosition |&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>findSlotByPaths() 获取插槽</h2>
<p>根据路径获取插槽。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">findSlotByPaths</span>(paths:&nbsp;<span class="tb-hl-builtin">number</span>[]): Slot |&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;slot = selection.<span class="tb-hl-function">findSlotByPaths</span>([<span class="tb-hl-number">0</span>,&nbsp;<span class="tb-hl-number">3</span>,&nbsp;<span class="tb-hl-number">55</span>])</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>findComponentByPaths() 获取组件</h2>
<p><span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">根据路径获取组件。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">findComponentByPaths</span>(paths:&nbsp;<span class="tb-hl-builtin">number</span>[]): ComponentInstance |&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">示例：</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;componentInstance = selection.<span class="tb-hl-function">findComponentByPaths</span>([<span class="tb-hl-number">0</span>,&nbsp;<span class="tb-hl-number">3</span>,&nbsp;<span class="tb-hl-number">55</span>,&nbsp;<span class="tb-hl-number">8</span>])</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2 style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">getSelectedScopes() 获取选中区域</span></h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">获取选区内所有的插槽片段集合。当&nbsp;<span style="background-color:rgb(254, 254, 254);font-family:&quot;Microsoft YaHei Mono&quot;, Menlo, Monaco, Consolas, &quot;Courier New&quot;, monospace">decompose 参数为 true 时，会把已选区中区域再按每个区域内容数据类型以块（Block）的方式再次拆分。</span></span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-comment">/**</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* 获取选区所选择的块的集合</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* @param decompose 是否按块分解已选中的区域</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;*/</span></div><div class="tb-code-line"><span class="tb-hl-function">getSelectedScopes</span>(decompose?:&nbsp;<span class="tb-hl-builtin">boolean</span>): SlotRange[];</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>SlotRange 结构如下：</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">SlotRange</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;slot: Slot;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;startIndex:&nbsp;<span class="tb-hl-builtin">number</span>;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;endIndex:&nbsp;<span class="tb-hl-builtin">number</span>;</div><div class="tb-code-line">}</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p><span style="color:rgb(73, 80, 96)">当选区如下时：</span></p><pre lang="HTML" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">&lt;<span class="tb-hl-tag">Component</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">Slot</span>&gt;xxxx【xxxx&lt;/<span class="tb-hl-tag">Slot</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">Component</span>&gt;</div><div class="tb-code-line">xxxxx</div><div class="tb-code-line">&lt;<span class="tb-hl-tag">Compoonent</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">Slot</span>&gt;xxxx&lt;/<span class="tb-hl-tag">Slot</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">Component</span>&gt;</div><div class="tb-code-line">&lt;<span class="tb-hl-tag">Compoonent</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">Slot</span>&gt;xxxx&lt;/<span class="tb-hl-tag">Slot</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">Slot</span>&gt;xx】xx&lt;/<span class="tb-hl-tag">Slot</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">Component</span>&gt;</div></div><span class="tb-pre-lang">HTML</span></div></pre>
<p>获取的结果如下：</p><pre lang="HTML" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">&lt;<span class="tb-hl-tag">Component</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">Slot</span>&gt;xxxx[xxxx]&lt;/<span class="tb-hl-tag">Slot</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">Component</span>&gt;</div><div class="tb-code-line">[xxxxx</div><div class="tb-code-line">&lt;<span class="tb-hl-tag">Compoonent</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">Slot</span>&gt;xxxx&lt;/<span class="tb-hl-tag">Slot</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">Component</span>&gt;]</div><div class="tb-code-line">&lt;<span class="tb-hl-tag">Compoonent</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">Slot</span>&gt;[xxxx]&lt;/<span class="tb-hl-tag">Slot</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">Slot</span>&gt;[xx]xx&lt;/<span class="tb-hl-tag">Slot</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">Component</span>&gt;</div></div><span class="tb-pre-lang">HTML</span></div></pre>
<tb-alert data-type="primary" class="tb-alert tb-alert-primary">
  <div><strong style="color:rgb(246, 48, 48)">提示：</strong>【】表格选区开始位置和结束位置，[] 表格获取的分段开始位置和结束位置。</div>
</tb-alert>
<h2>getRanges() 获取选区内的 Range 片段</h2>
<p>主要用于适配部分组件需要多选区的需求。由于默认的选区默认为一个连续的，根据文档流的结构，返回的文档片段。但有时我们需要多个不连续的选区，如表格。</p>
<p>getRanges 返回一个数组，默认返回一个 Range 片段，且和 Selection 的开始和结束位置一样。当组件通过 onGetRange 勾子自定义 Range 时，这里返回定制后的结果。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">getRanges</span>(): Range[];</div></div><span class="tb-pre-lang">TypeScript</span></div></pre><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">/**</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;* 选区开始和结果位置</span></div><div class="tb-code-line"><span class="tb-hl-comment">&nbsp;*/</span></div><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">Range</span>&nbsp;{</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;startSlot: Slot;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;endSlot: Slot;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;startOffset:&nbsp;<span class="tb-hl-builtin">number</span>;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;endOffset:&nbsp;<span class="tb-hl-builtin">number</span>;</div><div class="tb-code-line">}</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2 style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">getGreedyScopes() 获取选中 Block 范围</span></h2>
<p style="background-color:rgb(255, 255, 255)"><span style="color:rgb(73, 80, 96)">当当前选区的开始位置或结束位置为行内内容时，则会分别向前或向后把选区扩大到最近的块级内容边界。然后再获取边界内选中的范围，返回数据结构和 getSelectedScopes 一致。</span></p>
<h2>getBlocks() 获取选中的块</h2>
<p>在 getGreedyScopes 方法返回版本的基础上，把已选中的范围内所有子插槽全部拆分出来，并返回。返回数据结构和 getSelectedScopes 一致。</p>
<h2>getSlotRangeInCommonAncestorComponent() 获取范围</h2>
<p>获取开始插槽和结束插槽在公共组件内的下标范围。</p>
<h2>findFirstPosition() 获取插槽第一个位置</h2>
<p>获取插槽内第一个选区位置。如 toChild 为 true，则会在当插槽第一个内容为组件，且该组件还有子插槽时，继续向内查找。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">findFirstPosition</span>(slot: Slot, toChild?:&nbsp;<span class="tb-hl-builtin">boolean</span>): SelectionPosition;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>findLastPosition() 获取插槽最后一个位置</h2>
<p>获取插槽内最后一个选区位置。<span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">如 toChild 为 true，则会在当插槽最后一个内容为组件，且该组件还有子插槽时，继续向内查找。</span></p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">findLastPosition</span>(slot: Slot, toChild?:&nbsp;<span class="tb-hl-builtin">boolean</span>): SelectionPosition;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>getCommonAncestorSlotScope() 获取公共插槽</h2>
<p>获取当前选区在公共插槽的位置。</p>
<h2>getPathsBySlot() 获取插槽路径</h2>
<p>获取插槽在文档中的绝对路径，当插槽不在文档中时，返回 null。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">getPathsBySlot</span>(slot: Slot):&nbsp;<span class="tb-hl-builtin">number</span>[] |&nbsp;<span class="tb-hl-keyword">null</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>getNextPositionByPosition() 获取后一个位置</h2>
<p>根据指定位置，获取后一个光标位置。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">getNextPositionByPosition</span>(slot: Slot, offset:&nbsp;<span class="tb-hl-builtin">number</span>): SelectionPosition;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>getPreviousPositionByByPosition() 获取前一个位置</h2>
<p>根据指定位置，获取前一个光标位置。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">getPreviousPositionByPosition</span>(slot: Slot, offset:&nbsp;<span class="tb-hl-builtin">number</span>): SelectionPosition;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>getScopes() 获取范围</h2>
<p>根据指定的开始和结束位置，获取该区域的范围。</p><pre lang="TypeScript" theme="dark" class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名：</span></div><div class="tb-code-line"><span class="tb-hl-function">getScopes</span>(startSlot: Slot, startIndex:&nbsp;<span class="tb-hl-builtin">number</span>, endSlot: Slot, endIndex:&nbsp;<span class="tb-hl-builtin">number</span>, discardEmptyScope?:&nbsp;<span class="tb-hl-builtin">boolean</span>): SlotRange[];</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
  </div>
</template>