<script setup lang="ts">
import { useDocUpdate } from '@/hooks/use-doc-update';
import { ref } from 'vue';

const doc = ref<HTMLElement>()
useDocUpdate(doc)
</script>
<template>
  <div ref="doc">
    <h1>Selection 选区</h1>
<h2>onChange</h2>
<p>当选区变化时触发。</p>
<h2>isSelected</h2>
<p>是否有选区。</p>
<h2>isCollapsed</h2>
<p>选区是否是闭合的。</p>
<h2>startSlot</h2>
<p>选区开始的插槽。</p>
<h2>endSlot</h2>
<p>选区结束的插槽。</p>
<h2>startOffset</h2>
<p>选区开始的偏移量。</p>
<h2>endOffset</h2>
<p>选区结束的偏移量。</p>
<h2>anchorSlot</h2>
<p>锚点插槽。</p>
<h2>focusSlot</h2>
<p>焦点插槽。</p>
<h2>anchorOffset</h2>
<p>锚点偏移量。</p>
<h2>focusOffset</h2>
<p>焦点偏移量。</p>
<h2>commonAncestorSlot</h2>
<p>公共父插槽。</p>
<h2>commonAncestorComponent</h2>
<p>公共父组件。</p>
<h2>setStart()</h2>
<p>设置选区开始位置。</p>
<h2>setEnd()</h2>
<p>设置选区结构位置。</p>
<h2>setPosition()</h2>
<p>设置选区位置。</p>
<h2>selectComponent()</h2>
<p>选中一个组件。</p>
<h2>getSelectedScopes()</h2>
<p>获取选区内所有的插槽片段集合。</p>
<h2>toPrevious()</h2>
<p>光标移动到前一个位置。</p>
<h2>toNext()</h2>
<p>光标移动到后一个位置。</p>
<h2>toPreviousLine()</h2>
<p>光标移动到上一行。</p>
<h2>toNextLine()</h2>
<p>光标移动到下一行。</p>
<h2>wrapToAfter()</h2>
<p>向后框选。</p>
<h2>wrapToBefore()</h2>
<p>向前框选。</p>
<h2>wrapToTop()</h2>
<p>向上框选。</p>
<h2>wrapToBottom()</h2>
<p>向下框选。</p>
<h2>collapse()</h2>
<p>闭合选区。</p>
<h2>restore()</h2>
<p>同步 Textbus 选区到原生选区。</p>
<h2>getPaths()</h2>
<p>获取选区路径。</p>
<h2>usePaths()</h2>
<p>使用选区路径。</p>
<h2>unSelect()</h2>
<p>取消选区。</p>
<h2>selectAll()</h2>
<p>全选。</p>
<h2>getNextPosition()</h2>
<p>获取后一个选区位置。</p>
<h2>getPreviousPosition()</h2>
<p>获取前一个选区位置。</p>
<h2>findSlotByPaths()</h2>
<p>根据路径获取插槽。</p>
<h2>findComponentByPaths()</h2>
<p>根据路径获取组件。</p>
<h2>getBlocks()</h2>
<p>获取选区内块级区域。</p>
<h2>getSlotRangeInCommonAncestorComponent()</h2>
<p>获取开始插槽和结束插槽在公共组件内的下标范围。</p>
<h2>getGreedyScopes()</h2>
<p>获取当前选区在开始和结束位置均扩展到最大行内内容位置是的块。</p>
<h2>findFirstPosition()</h2>
<p>获取插槽内第一个选区位置。</p>
<h2>findLastPosition()</h2>
<p>获取插槽内最后一个选区位置。</p>
<h2>getCommonAncestorSlotScope()</h2>
<p>获取当前选区在公共插槽的位置。</p>
  </div>
</template>