import { inject, createDynamicRef } from '@viewfly/core'
import { ViewUpdateInjectionToken } from '../../injection-tokens'
export default function() {
  const subject = inject(ViewUpdateInjectionToken)
  const ref = createDynamicRef(node => {
    subject.next(node as HTMLElement)
  })
  return function() {
    return (
      <div ref={ref}><h1>协作光标</h1>
<p><span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">CollaborateCursor 类用于&nbsp;</span>Textbus 进行多人协作编辑时，在编辑器内实时显示用户的光标和选区。</p>
<p><span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">通过编辑器实例或通过 useContext 勾子获取 CollaborateCursor 的实例。</span></p><pre lang="TypeScript" theme="dark" line-number class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 方法1</span></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;collaborateCursor = textbus.<span class="tb-hl-function">get</span>(CollaborateCursor)</div><div class="tb-code-line"><span class="tb-hl-comment">// 方法2</span></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;yourComponent =&nbsp;<span class="tb-hl-function">defineComponent</span>({'{'}</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-function">setup</span>() {'{'}</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">const</span>&nbsp;collaborateCursor =&nbsp;<span class="tb-hl-function">useContext</span>(CollaborateCursor)</div><div class="tb-code-line">&nbsp;&nbsp;{'}'}</div><div class="tb-code-line">{'}'})</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>refresh() 刷新协作光标</h2>
<p>用于刷新多用户在文档内的虚拟光标或选区，当文档内容发生变化或窗口缩放时会自动调用。出于性能的原因，Textbus 只会绘制可见区域的协作光标，并且 Textbus 无法预见你会把文档放在哪一个可滚动的 DOM 容器内，无法做到监听，所以，当文档发生滚动时，<span style="background-color:rgb(255, 255, 255);color:rgb(73, 80, 96)">需要你手动调用</span>。</p>
<p>如文档在某个 DIV 内：</p><pre lang="TypeScript" theme="dark" line-number class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">div.<span class="tb-hl-function">addEventListener</span>(<span class="tb-hl-string">'scroll'</span>, () =&gt; {'{'}</div><div class="tb-code-line">&nbsp;&nbsp;collaborateCursor.<span class="tb-hl-function">refresh</span>()</div><div class="tb-code-line">{'}'})</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<h2>destroy() 销毁</h2>
<p>用于销毁，无需手动调用。</p>
<h2>draw() 更新协作光标</h2>
<p>用于当协作光标位置变化时，重新在文档中绘制协作光标。</p><pre lang="TypeScript" theme="dark" line-number class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">import</span>&nbsp;{'{'} SelectionPaths {'}'}&nbsp;<span class="tb-hl-keyword">from</span>&nbsp;<span class="tb-hl-string">'@textbus/core'</span>;</div><div class="tb-code-line"><span class="tb-hl-keyword">export</span>&nbsp;<span class="tb-hl-keyword">interface</span>&nbsp;<span class="tb-hl-class-name">RemoteSelection</span>&nbsp;{'{'}</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;id:&nbsp;<span class="tb-hl-builtin">string</span>;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;color:&nbsp;<span class="tb-hl-builtin">string</span>;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;username:&nbsp;<span class="tb-hl-builtin">string</span>;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;paths: SelectionPaths;</div><div class="tb-code-line">{'}'}</div></div><span class="tb-pre-lang">TypeScript</span></div></pre><pre lang="TypeScript" theme="dark" line-number class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-comment">// 类型签名</span></div><div class="tb-code-line"><span class="tb-hl-function">draw</span>(paths: RemoteSelection[]):&nbsp;<span class="tb-hl-keyword">void</span>;</div></div><span class="tb-pre-lang">TypeScript</span></div></pre>
<p>示例：</p><pre lang="TypeScript" theme="dark" line-number class="tb-pre"><div class="tb-pre-content"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">collaborateCursor.<span class="tb-hl-function">draw</span>([{'{'}</div><div class="tb-code-line">&nbsp;&nbsp;id:&nbsp;<span class="tb-hl-string">'用户 ID'</span>,</div><div class="tb-code-line">&nbsp;&nbsp;color:&nbsp;<span class="tb-hl-string">'#f00'</span>,</div><div class="tb-code-line">&nbsp;&nbsp;username:&nbsp;<span class="tb-hl-string">'张三'</span>,</div><div class="tb-code-line">&nbsp;&nbsp;paths: [...]&nbsp;<span class="tb-hl-comment">// 协作光标路径，可参考 Selection.getPaths() 返回的数据</span></div><div class="tb-code-line">{'}'}])</div></div><span class="tb-pre-lang">TypeScript</span></div></pre></div>
    )
  }
}