<script setup lang="ts">
import { useDocUpdate } from '@/hooks/use-doc-update';
import { ref } from 'vue';

const doc = ref<HTMLElement>()
useDocUpdate(doc)
</script>
<template>
  <div ref="doc">
    <h1>开始</h1>
<p>Textbus 是一个以组件为中心，数据驱动的富文本编辑器开发框架！</p>
<p>为了解决传统富文本开发中遇到的各种问题，我们完全自主设计了富文本的组件系统和格式系统，旨在降低富文本的开发成本，帮助你更轻松的扩展出丰富的富文本功能。不管你是富文本开发的老鸟，亦或是前端的新手，你都将会在 Textbus 中感受到非凡的开发体验和扩展能力。</p>
<p>鉴于大多数人仅需要一个开箱即用的编辑器，Textbus 在开发内核的同时，也同步开发了相应的编辑器，即你在官网看到的编辑器。你可以直接使用它，而不需要关注太多细节。</p>
<tb-alert data-type="default" class="tb-alert tb-alert-default">
  <div><strong>提示：</strong>如果你需要自定义编辑器，或者是想做出类似钉钉文档、石墨文档的产品，现有的编辑器可能满足不了你的需求，你可以移步<a target="_self" href="https://textbus.io/docs/guide">开发指南</a>。</div>
</tb-alert>
<p>让我们开始吧！</p>
<h2>安装</h2>
<p>通过 npm 安装 Textbus：</p><pre lang="" theme="null" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">npm install @textbus/editor</div></div><span class="tb-pre-lang"></span></pre>
<p>准备好一个 DOM 元素。</p><pre lang="HTML" theme="null" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">&lt;<span class="tb-hl-tag">div&nbsp;</span><span class="tb-hl-attr-name">id</span>="<span class="tb-hl-attr-value">editor</span>"&gt;&lt;/<span class="tb-hl-tag">div</span>&gt;</div></div><span class="tb-pre-lang">HTML</span></pre>
<p>创建一个编辑器。</p><pre lang="TypeScript" theme="null" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">import</span>&nbsp;<span class="tb-hl-string">"@textbus/editor/bundles/textbus.min.css"</span></div><div class="tb-code-line"><span class="tb-hl-keyword">import</span>&nbsp;{ createEditor }&nbsp;<span class="tb-hl-keyword">from</span>&nbsp;<span class="tb-hl-string">'@textbus/editor'</span></div><div class="tb-code-line"><br></div><div class="tb-code-line"><span class="tb-hl-keyword">const</span>&nbsp;editor =&nbsp;<span class="tb-hl-function">createEditor</span>()</div><div class="tb-code-line">editor.<span class="tb-hl-function">mount</span>(document.<span class="tb-hl-function">getElementById</span>(<span class="tb-hl-string">'editor'</span>))</div><div class="tb-code-line"><br></div><div class="tb-code-line"><span class="tb-hl-comment">// 监听数据变化，并获取编辑结果</span></div><div class="tb-code-line">editor.onChange.<span class="tb-hl-function">subscribe</span>(() =&gt; {</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-keyword">const</span>&nbsp;html = editor.<span class="tb-hl-function">getHTML</span>()</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-builtin">console</span>.<span class="tb-hl-function">log</span>(html)</div><div class="tb-code-line">})</div></div><span class="tb-pre-lang">TypeScript</span></pre>
<p>现在我们的编辑器就创建好了。</p>
<h2>通过标签引入</h2>
<p>如果你是传统的项目，你可以通过标签引入。</p>
<p>点击下载&nbsp;<a target="_blank" href="https://textbus.io/lib/textbus.min.js">textbus.m​in.js</a>&nbsp;<a target="_blank" href="https://textbus.io/lib/textbus.min.css">textbus.m​in.css</a>。</p><pre lang="Jsx" theme="null" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">&lt;!DOCTYPE html&gt;</div><div class="tb-code-line">&lt;<span class="tb-hl-tag">html</span>&gt;</div><div class="tb-code-line">&lt;<span class="tb-hl-tag">head</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">link&nbsp;</span><span class="tb-hl-attr-name">rel</span>="<span class="tb-hl-attr-value">stylesheet</span>"<span class="tb-hl-tag">&nbsp;</span><span class="tb-hl-attr-name">href</span>="<span class="tb-hl-attr-value">https://textbus.io/lib/textbus.min.css</span>"&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">script&nbsp;</span><span class="tb-hl-attr-name">src</span>="<span class="tb-hl-attr-value">https://textbus.io/lib/textbus.min.js</span>"&gt;&lt;/<span class="tb-hl-tag">script</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">head</span>&gt;</div><div class="tb-code-line">&lt;<span class="tb-hl-tag">body</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">div&nbsp;</span><span class="tb-hl-attr-name">id</span>="<span class="tb-hl-attr-value">editor</span>"&gt;&lt;/<span class="tb-hl-tag">div</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&lt;<span class="tb-hl-tag">script</span>&gt;</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">var</span>&nbsp;editor = textbus.editor.<span class="tb-hl-function">createEditor</span>()</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;editor.<span class="tb-hl-function">mount</span>(document.<span class="tb-hl-function">getElementById</span>(<span class="tb-hl-string">'editor'</span>))</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;editor.onChange.<span class="tb-hl-function">subscribe</span>(<span class="tb-hl-keyword">function</span>() {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">const</span>&nbsp;html = editor.<span class="tb-hl-function">getHTML</span>()</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;console.<span class="tb-hl-function">log</span>(html)</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;})</div><div class="tb-code-line">&nbsp;&nbsp;&lt;/<span class="tb-hl-tag">script</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">body</span>&gt;</div><div class="tb-code-line">&lt;/<span class="tb-hl-tag">html</span>&gt;</div></div><span class="tb-pre-lang">Jsx</span></pre>
<h2>浏览器兼容</h2>
<p>Textbus 兼容现代浏览器，包括 Chrome、Firefox、Safari、Edge 等。</p>
<h3>兼容补丁</h3>
<p>已知 Firefox 不支持&nbsp;<code>Intl.Segmenter</code>，需要在 Textbus 启动之前打上特定补丁。</p><pre lang="" theme="null" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line">npm install intl-segmenter-polyfill</div></div><span class="tb-pre-lang"></span></pre>
<p>在 Textbus 启动时，打上补丁</p><pre lang="TypeScript" theme="null" class="tb-pre"><div style="width:2.5em" class="tb-code-line-number-bg"></div><div class="tb-code-content"><div class="tb-code-line"><span class="tb-hl-keyword">import</span>&nbsp;{ createEditor }&nbsp;<span class="tb-hl-keyword">from</span>&nbsp;<span class="tb-hl-string">'@textbus/editor'</span></div><div class="tb-code-line"><br></div><div class="tb-code-line"><span class="tb-hl-keyword">async</span>&nbsp;<span class="tb-hl-keyword">function</span>&nbsp;<span class="tb-hl-function">create</span>() {</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-keyword">if</span>&nbsp;(!Intl.Segmenter) {</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;<span class="tb-hl-keyword">const</span>&nbsp;polyfill =&nbsp;<span class="tb-hl-keyword">await</span>&nbsp;<span class="tb-hl-keyword">import</span>(<span class="tb-hl-string">'intl-segmenter-polyfill/dist/bundled'</span>);</div><div class="tb-code-line">&nbsp;&nbsp;&nbsp;&nbsp;(Intl&nbsp;<span class="tb-hl-keyword">as</span>&nbsp;<span class="tb-hl-builtin">any</span>).Segmenter =&nbsp;<span class="tb-hl-keyword">await</span>&nbsp;polyfill.<span class="tb-hl-function">createIntlSegmenterPolyfill</span>()</div><div class="tb-code-line">&nbsp;&nbsp;}</div><div class="tb-code-line"><br></div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-keyword">return</span>&nbsp;<span class="tb-hl-function">createEditor</span>()</div><div class="tb-code-line">}</div><div class="tb-code-line"><br></div><div class="tb-code-line"><span class="tb-hl-function">create</span>().<span class="tb-hl-function">then</span>(editor =&gt; {</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-keyword">const</span>&nbsp;container = document.<span class="tb-hl-function">getElementById</span>(<span class="tb-hl-string">'editor'</span>)</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-keyword">return</span>&nbsp;editor.<span class="tb-hl-function">mount</span>(container)</div><div class="tb-code-line">}).<span class="tb-hl-function">then</span>(() =&gt; {</div><div class="tb-code-line">&nbsp;&nbsp;<span class="tb-hl-builtin">console</span>.<span class="tb-hl-function">log</span>(<span class="tb-hl-string">'编辑器创建成功！'</span>)</div><div class="tb-code-line">})</div></div><span class="tb-pre-lang">TypeScript</span></pre>
  </div>
</template>